language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: j6l5+1eC9ULHzd8SCSnjxxOLBTGknjwG2vQOneTkjHi+SWWYkE327l1hIItbHzlPE/ORd+/gG/PBe3P8QyHoxWdixmDGbKiQRwZ5xga6pKwik5SA0vEWoRQAdeMMBHoVBz0/yIvvcSrvwLrbRMpgt816iRBBTUvHwZZXDzVWkZ8r7DtiUI12orktFfmdcLq4SEcfScs5Kamww31Qp2+DnKpg/w+2h1tHBwPn7Q48g4n0eS38QGWvnbNc+LL/3fR1E+pSuXlULFuwsZSfPDRXIUQf+hl6UgOVN/6qmyViFZTYvhAU8hRXA9gWcE7z3QLpMrf2+CuhYFz2yoX5duvz+4GMmZBcAYqs37DMHZQwIK1gmFsV35ArY2NN7QppJIZFFFsmcIduj3C3KLe1T201Iv8MQUtEO84vndTB5/aswpvgFSbgEGatmc9hlip3GT3Vj6nLMAaZDtquIZCZPKkOfxr600VlXYRgYKmRaLLQrapjEECjg1oy55ML5XN/bqShr09vlwCXEzRtg+/oWVDYD2DqorIuhmiqHjlORdRHWlbZVitp1lUKM/H7JjxsVN+fCrWiTOQqnH2n9lJLNx+9TAKt8mSzGIFP6/wLcC69YjyOa8oSlIY9qVvOVRA0e2UR6QF+oxBMsRVkN94hUljziL8fIPXnV0ITYQIuuCgfoBQ=
  app: managecare
